#spring:
#  application:
#    name: ad-eureka
#
#server:
#  port: 9000
##eureka:
##  instance:
##    hostname: localhost
##  client:
##    fetch-registry: false
##    register-with-eureka: false
##    service-url:
##      defaultZone: http://${eureka.instance.hostname}:${server.port}
#
#
---
spring:
  application:
    name: ad-eureka
profiles: server1
server:
  port: 9000
eureka:
  instance:
    hostname: server1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server2:9001/eureka/,http://server3:9002/eureka/
---
spring:
  application:
    name: ad-eureka
  profiles: server2
server:
  port: 9001
eureka:
  instance:
    hostname: server2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:9000/eureka/,http://server3:9002/eureka/
---
spring:
  application:
    name: ad-eureka
  profiles: server3
server:
  port: 9002
eureka:
  instance:
    hostname: server3
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:9000/eureka/,http://server2:9001/eureka/
